package com.crud.sample.beans;
// Generated Dec 19, 2016 7:47:02 PM by Hibernate Tools 3.6.0.Final

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * SsoApplications generated by hbm2java
 */
@Entity
@JsonIgnoreProperties(ignoreUnknown = true)
//@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property="id")
@Table(name = "SSO_APPLICATIONS")
public class SsoApplications implements java.io.Serializable {

	private double id;
	private SsoCategories ssoCategories;
	private String name;
	private String createdBy;
	private Date createdDt;
	private String updatedBy;
	private Date updatedDt;
	private String statusFlg;
	private String url;

	public SsoApplications() {
	}

	public SsoApplications(double id, SsoCategories ssoCategories, String name, String createdBy, Date createdDt,
			String statusFlg, String url) {
		this.id = id;
		this.ssoCategories = ssoCategories;
		this.name = name;
		this.createdBy = createdBy;
		this.createdDt = createdDt;
		this.statusFlg = statusFlg;
		this.url = url;
	}

	public SsoApplications(double id, SsoCategories ssoCategories, String name, String createdBy, Date createdDt,
			String updatedBy, Date updatedDt, String statusFlg, String url) {
		this.id = id;
		this.ssoCategories = ssoCategories;
		this.name = name;
		this.createdBy = createdBy;
		this.createdDt = createdDt;
		this.updatedBy = updatedBy;
		this.updatedDt = updatedDt;
		this.statusFlg = statusFlg;
		this.url = url;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public double getId() {
		return this.id;
	}

	public void setId(double id) {
		this.id = id;
	}

	
	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.ALL)	
	@JoinColumn(name = "CATEGORY_FK")
	@Fetch(FetchMode.JOIN)
	//@JsonBackReference
	public SsoCategories getSsoCategories() {
		return this.ssoCategories;
	}

	public void setSsoCategories(SsoCategories ssoCategories) {
		this.ssoCategories = ssoCategories;
	}

	@Column(name = "NAME", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 100)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DT", nullable = false)
	public Date getCreatedDt() {
		return this.createdDt;
	}

	public void setCreatedDt(Date createdDt) {
		this.createdDt = createdDt;
	}

	@Column(name = "UPDATED_BY", length = 100)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATED_DT")
	public Date getUpdatedDt() {
		return this.updatedDt;
	}

	public void setUpdatedDt(Date updatedDt) {
		this.updatedDt = updatedDt;
	}

	@Column(name = "STATUS_FLG", nullable = false, length = 2)
	public String getStatusFlg() {
		return this.statusFlg;
	}

	public void setStatusFlg(String statusFlg) {
		this.statusFlg = statusFlg;
	}

	@Column(name = "URL", nullable = false, length = 256)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

}
